version: "3.7"

services:
  api:
    container_name: shortify-api
    build:
      context: .
      dockerfile: Dockerfile
    image: shortify-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env.docker
    networks:
      - shortify-network
  db:
    container_name: shortify-db
    image: redis:5.0.5-alpine
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - shortify-network

networks:
  shortify-network:
    driver: bridge
