version: "3.7"

services:
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - api/.env

  db:
    container_name: db
    build: 
      context: db
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"