name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checking code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      # We 1st need to change dir to run the tests
      - name: Copy .env.example to .env
        run: cd ./api/tests && cp .env.example .env

      - name: Run Unit Tests
        run: cd ./api && go test -v ./tests/...
